{
    "type": "bundle",
    "id": "bundle--204b5953-acaa-4b1f-92bd-5f351cd92d69",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--05ed2242-368b-4a5e-b5c0-8be17c93d6fc",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-15T00:22:01.839322Z",
            "modified": "2025-04-15T00:22:01.839322Z",
            "name": "CVE-2025-32908",
            "description": "A flaw was found in libsoup. The HTTP/2 server in libsoup may not fully validate the values of pseudo-headers :scheme, :authority, and :path, which may allow a user to cause a denial of service (DoS).",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32908"
                }
            ]
        }
    ]
}