{
    "type": "bundle",
    "id": "bundle--f4c2c8bd-33d9-45f8-ada3-148f4abef830",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--dde0b443-cf0b-48d9-a8cc-7b871d9e3995",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-20T00:20:33.096017Z",
            "modified": "2025-03-20T00:20:33.096017Z",
            "name": "CVE-2024-25132",
            "description": "A flaw was found in the Hive hibernation controller component of OpenShift Dedicated. The ClusterDeployment.hive.openshift.io/v1 resource can be created with the spec.installed field set to true, regardless of the installation status, and a positive timespan for the spec.hibernateAfter value. If a ClusterSync.hiveinternal.openshift.io/v1alpha1 resource is also created, the hive hibernation controller will enter the reconciliation loop leading to a panic when accessing a non-existing field in the ClusterDeploymentâ€™s status section, resulting in a denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-25132"
                }
            ]
        }
    ]
}