{
    "type": "bundle",
    "id": "bundle--a3ce888c-2b64-4404-958b-832ed64684d2",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--26a8c450-39b0-43e7-80e4-cd94fef937d0",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-06-01T00:27:54.719862Z",
            "modified": "2025-06-01T00:27:54.719862Z",
            "name": "CVE-2018-25111",
            "description": "django-helpdesk before 1.0.0 allows Sensitive Data Exposure because of os.umask(0) in models.py.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2018-25111"
                }
            ]
        }
    ]
}