{
    "type": "bundle",
    "id": "bundle--45d33794-5113-4efb-a0b9-91afcae7931f",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--7ba65779-5fe4-46c0-af7b-f5af8208399b",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-01-22T00:19:38.609895Z",
            "modified": "2025-01-22T00:19:38.609895Z",
            "name": "CVE-2024-49747",
            "description": "In gatts_process_read_by_type_req of gatt_sr.cc, there is a possible out of bounds write due to a logic error in the code. This could lead to remote code execution with no additional execution privileges needed. User interaction is not needed for exploitation.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-49747"
                }
            ]
        }
    ]
}