{
    "type": "bundle",
    "id": "bundle--d4bbc83c-1b63-4100-afc5-f7cbc67132bf",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ed0ade70-0d8f-47a3-b3e6-d8d3b7f70407",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-12-30T00:20:41.111761Z",
            "modified": "2024-12-30T00:20:41.111761Z",
            "name": "CVE-2024-56606",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\naf_packet: avoid erroring out after sock_init_data() in packet_create()\n\nAfter sock_init_data() the allocated sk object is attached to the provided\nsock object. On error, packet_create() frees the sk object leaving the\ndangling pointer in the sock object on return. Some other code may try\nto use this pointer and cause use-after-free.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-56606"
                }
            ]
        }
    ]
}