{
    "type": "bundle",
    "id": "bundle--4d6d2b62-1124-422b-b975-7b23f3822a93",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--b824a60c-c06a-4ab2-bf9d-6a76b7ae4747",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-09T00:21:18.231196Z",
            "modified": "2025-04-09T00:21:18.231196Z",
            "name": "CVE-2025-32414",
            "description": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Python API (Python bindings) because of an incorrect return value. This occurs in xmlPythonFileRead and xmlPythonFileReadRaw because of a difference between bytes and characters.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32414"
                }
            ]
        }
    ]
}