{
    "type": "bundle",
    "id": "bundle--ee455aed-97b9-4b42-a571-949a2921dd47",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--119cafa1-cd62-45ab-8d74-caaebe1c26c4",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-27T00:20:50.796587Z",
            "modified": "2025-03-27T00:20:50.796587Z",
            "name": "CVE-2025-31160",
            "description": "atop through 2.11.0 allows local users to cause a denial of service (e.g., assertion failure and application exit) or possibly have unspecified other impact by running certain types of unprivileged processes while a different user runs atop.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-31160"
                }
            ]
        }
    ]
}