{
    "type": "bundle",
    "id": "bundle--9dbc0b93-a47f-4c56-8606-14fad69d0172",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--923dff76-0e7f-4eed-a7d9-4a98b9936a9c",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-11-14T00:19:17.044595Z",
            "modified": "2024-11-14T00:19:17.044595Z",
            "name": "CVE-2024-37400",
            "description": "An out of bounds read in Ivanti Connect Secure before version 22.7R2.3 allows a remote unauthenticated attacker to trigger an infinite loop, causing a denial of service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-37400"
                }
            ]
        }
    ]
}