{
    "type": "bundle",
    "id": "bundle--2e6bf598-85a1-4291-9ef8-c6d1ab046750",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--87dc4bb9-185a-4168-a6a0-49f15fb5ec9e",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-02-27T00:20:15.627609Z",
            "modified": "2025-02-27T00:20:15.627609Z",
            "name": "CVE-2022-49388",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nubi: ubi_create_volume: Fix use-after-free when volume creation failed\n\nThere is an use-after-free problem for 'eba_tbl' in ubi_create_volume()'s\nerror handling path:\n\n  ubi_eba_replace_table(vol, eba_tbl)\n    vol->eba_tbl = tbl\nout_mapping:\n  ubi_eba_destroy_table(eba_tbl)   // Free 'eba_tbl'\nout_unlock:\n  put_device(&vol->dev)\n    vol_release\n      kfree(tbl->entries)\t  // UAF\n\nFix it by removing redundant 'eba_tbl' releasing.\nFetch a reproducer in [Link].",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-49388"
                }
            ]
        }
    ]
}