{
    "type": "bundle",
    "id": "bundle--a324dbc3-6366-431c-92b6-90cf86686d4c",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--370d5e9b-3b7a-473d-926c-bde2f7e901c5",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-11T00:20:51.310699Z",
            "modified": "2025-03-11T00:20:51.310699Z",
            "name": "CVE-2022-48610",
            "description": "This issue was addressed through improved state management. This issue is fixed in macOS Ventura 13.1, watchOS 9.2, iOS 16.2 and iPadOS 16.2. An app may be able to access user-sensitive data.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-48610"
                }
            ]
        }
    ]
}