{
    "type": "bundle",
    "id": "bundle--c178cf19-7cb4-4103-aa3e-29cd1e053b7a",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--811ee977-479e-4eaf-bc24-c9221d12cefa",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-11T00:21:41.324747Z",
            "modified": "2025-04-11T00:21:41.324747Z",
            "name": "CVE-2025-32699",
            "description": "Vulnerability in Wikimedia Foundation MediaWiki, Wikimedia Foundation Parsoid.This issue affects MediaWiki: before 1.39.12, 1.42.6, 1.43.1; Parsoid: before 0.16.5, 0.19.2, 0.20.2.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32699"
                }
            ]
        }
    ]
}