{
    "type": "bundle",
    "id": "bundle--52285c22-c759-4fd9-a090-44051c557f3d",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--7088270d-7e91-4247-9239-528306a286c5",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-05-30T00:22:38.410572Z",
            "modified": "2025-05-30T00:22:38.410572Z",
            "name": "CVE-2025-37995",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nmodule: ensure that kobject_put() is safe for module type kobjects\n\nIn 'lookup_or_create_module_kobject()', an internal kobject is created\nusing 'module_ktype'. So call to 'kobject_put()' on error handling\npath causes an attempt to use an uninitialized completion pointer in\n'module_kobject_release()'. In this scenario, we just want to release\nkobject without an extra synchronization required for a regular module\nunloading process, so adding an extra check whether 'complete()' is\nactually required makes 'kobject_put()' safe.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-37995"
                }
            ]
        }
    ]
}